import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    AUTH_SECRET: z.string().min(32),
    AUTH_URL: z.string().url(),
    STRIPE_SECRET_KEY: z.string().startsWith('sk_'),
    STRIPE_WEBHOOK_SECRET: z.string().startsWith('whsec_'),
    BREVO_API_KEY: z.string().min(1),
    BREVO_SMS_SENDER: z.string().default('StrikePoint'),
    BREVO_TRANSACTIONAL_SENDER_EMAIL: z.string().email(),
    BREVO_TRANSACTIONAL_SENDER_NAME: z.string().default('StrikePoint Sims'),
    AI_PROVIDER: z.enum(['anthropic', 'google']).default('google'),
    ANTHROPIC_API_KEY: z.string().startsWith('sk-ant-').optional(),
    GOOGLE_AI_API_KEY: z.string().min(1).optional(),
    TRACKMAN_CONNECT_API_KEY: z.string().min(1).optional(),
    OPENPATH_API_BASE_URL: z.string().url(),
    OPENPATH_API_KEY: z.string().min(1),
    OPENPATH_ORG_ID: z.string().min(1),
    OPENPATH_MOCK_MODE: z.coerce.boolean().default(false),
    INNGEST_EVENT_KEY: z.string().min(1),
    INNGEST_SIGNING_KEY: z.string().startsWith('signkey-'),
    SENTRY_DSN: z.string().url().optional(),
    OWNER_EMAIL: z.string().email(),
    OWNER_PHONE: z.string().regex(/^\+1\d{10}$/),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_POSTHOG_KEY: z.string().min(1).optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().url().optional(),
    NEXT_PUBLIC_LOCATION_ID: z.string().min(1),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().startsWith('pk_'),
  },
  runtimeEnv: {
    DATABASE_URL: process.env['DATABASE_URL'],
    AUTH_SECRET: process.env['AUTH_SECRET'],
    AUTH_URL: process.env['AUTH_URL'],
    STRIPE_SECRET_KEY: process.env['STRIPE_SECRET_KEY'],
    STRIPE_WEBHOOK_SECRET: process.env['STRIPE_WEBHOOK_SECRET'],
    BREVO_API_KEY: process.env['BREVO_API_KEY'],
    BREVO_SMS_SENDER: process.env['BREVO_SMS_SENDER'],
    BREVO_TRANSACTIONAL_SENDER_EMAIL: process.env['BREVO_TRANSACTIONAL_SENDER_EMAIL'],
    BREVO_TRANSACTIONAL_SENDER_NAME: process.env['BREVO_TRANSACTIONAL_SENDER_NAME'],
    AI_PROVIDER: process.env['AI_PROVIDER'],
    ANTHROPIC_API_KEY: process.env['ANTHROPIC_API_KEY'],
    GOOGLE_AI_API_KEY: process.env['GOOGLE_AI_API_KEY'],
    TRACKMAN_CONNECT_API_KEY: process.env['TRACKMAN_CONNECT_API_KEY'],
    OPENPATH_API_BASE_URL: process.env['OPENPATH_API_BASE_URL'],
    OPENPATH_API_KEY: process.env['OPENPATH_API_KEY'],
    OPENPATH_ORG_ID: process.env['OPENPATH_ORG_ID'],
    OPENPATH_MOCK_MODE: process.env['OPENPATH_MOCK_MODE'],
    INNGEST_EVENT_KEY: process.env['INNGEST_EVENT_KEY'],
    INNGEST_SIGNING_KEY: process.env['INNGEST_SIGNING_KEY'],
    SENTRY_DSN: process.env['SENTRY_DSN'],
    OWNER_EMAIL: process.env['OWNER_EMAIL'],
    OWNER_PHONE: process.env['OWNER_PHONE'],
    NEXT_PUBLIC_APP_URL: process.env['NEXT_PUBLIC_APP_URL'],
    NEXT_PUBLIC_POSTHOG_KEY: process.env['NEXT_PUBLIC_POSTHOG_KEY'],
    NEXT_PUBLIC_POSTHOG_HOST: process.env['NEXT_PUBLIC_POSTHOG_HOST'],
    NEXT_PUBLIC_LOCATION_ID: process.env['NEXT_PUBLIC_LOCATION_ID'],
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env['NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY'],
  },
})
